"""
Get real on-device numbers from Qualcomm AI Hub, since anything measured on an x86
dev machine says nothing about how this runs on an actual Snapdragon NPU.

Uploads artifacts/uplift_int8.onnx, compiles it for a hosted Snapdragon X device,
profiles it there, and (optionally) runs the sample customers on the device to
confirm the on-device output matches the local model.

One-time setup (your token stays on your machine, never commit it):
    pip install qai-hub
    qai-hub configure --api_token YOUR_TOKEN

Run:
    python profile_on_ai_hub.py

Outputs:
    aihub_results.json   full record of the run (device, runtime, latency, memory, job URLs)
    aihub_results.js     same numbers, read by demo.html's telemetry panel

These numbers come from a hosted Snapdragon device on Qualcomm AI Hub, not from a
personal laptop - report them that way ("profiled on Qualcomm AI Hub, <device>").
"""
import argparse
import datetime
import json
import sys

import numpy as np

MODEL = "artifacts/uplift_int8.onnx"
SAMPLES = "artifacts/sample_inputs.npy"


def pick_device(hub, wanted):
    devices = hub.get_devices()
    if wanted:
        match = [d for d in devices if d.name == wanted]
        if match:
            return match[0]
        sys.exit(f"Device '{wanted}' not found. Run with --list-devices to see options.")
    # prefer Windows-on-Snapdragon laptops (what the challenge targets)
    cands = [d for d in devices if "Snapdragon X" in d.name]
    if not cands:
        cands = [d for d in devices if "Snapdragon" in d.name]
    if not cands:
        sys.exit("No Snapdragon devices returned by AI Hub. Re-run with --list-devices.")
    cands.sort(key=lambda d: ("Elite" not in d.name, d.name))  # Elite first
    return cands[0]


def parse_profile(profile):
    """Pull the headline numbers out of AI Hub's profile dict (defensive: keys may vary)."""
    es = profile.get("execution_summary", {}) or {}
    detail = profile.get("execution_detail", []) or es.get("execution_detail", []) or []

    def us_to_ms(v):
        return None if v is None else round(v / 1000.0, 4)

    units = {}
    for layer in detail:
        cu = layer.get("compute_unit", "unknown")
        units[cu] = units.get(cu, 0) + 1

    peak = es.get("estimated_inference_peak_memory")
    if isinstance(peak, (list, tuple)):       # some SDK versions return [min, max]
        peak = peak[-1]
    return {
        "inference_ms": us_to_ms(es.get("estimated_inference_time")),
        "first_load_ms": us_to_ms(es.get("first_load_time")),
        "warm_load_ms": us_to_ms(es.get("warm_load_time")),
        "peak_memory_mb": None if peak is None else round(peak / (1024 * 1024), 2),
        "layers_total": sum(units.values()),
        "layers_by_compute_unit": units,
    }


def save_results(result):
    with open("aihub_results.json", "w") as f:
        json.dump(result, f, indent=2)
    with open("aihub_results.js", "w") as f:
        f.write("// Auto-generated by profile_on_ai_hub.py\nconst AIHUB_RESULTS = " + json.dumps(result) + ";\n")


def match_uplift_output(out, local):
    """The compiled model may rename its outputs, so find the uplift output by VALUE:
    the on-device output closest to the local model's uplift. Returns (name, max_abs_diff)."""
    best = None
    for name, arrs in out.items():
        try:
            vals = np.array([np.asarray(a).ravel()[0] for a in arrs], dtype=float)
        except Exception:
            continue
        if vals.shape != local.shape:
            continue
        d = float(np.abs(vals - local).max())
        if best is None or d < best[1]:
            best = (name, d)
    return best


def inference_check(hub, inf_job):
    X = np.load(SAMPLES).astype(np.float32)
    out = inf_job.download_output_data()
    print("   on-device output names:", list(out.keys()))
    import onnxruntime as ort
    sess = ort.InferenceSession(MODEL, providers=["CPUExecutionProvider"])
    local = np.array([sess.run(["uplift"], {"features": X[i:i + 1]})[0][0, 0] for i in range(len(X))])
    return match_uplift_output(out, local)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--device", default="", help="exact AI Hub device name (default: a Snapdragon X Elite)")
    ap.add_argument("--list-devices", action="store_true")
    ap.add_argument("--skip-inference", action="store_true", help="skip the on-device correctness check")
    ap.add_argument("--profile-job", default="", help="reuse an existing profile job ID instead of resubmitting")
    ap.add_argument("--compile-job", default="", help="(with --profile-job) existing compile job ID")
    ap.add_argument("--inference-job", default="", help="reuse an existing inference job ID")
    ap.add_argument("--runtime", default="onnx", help="(resume only) target runtime used by the compile job")
    args = ap.parse_args()

    try:
        import qai_hub as hub
    except ImportError:
        sys.exit("qai_hub not installed. Run: pip install qai-hub")

    if args.list_devices:
        for d in hub.get_devices():
            print(d.name, "|", d.os)
        return

    if args.profile_job:                                   # ---- resume from existing jobs
        profile_job = hub.get_job(args.profile_job)
        compile_job = hub.get_job(args.compile_job) if args.compile_job else None
        device = getattr(profile_job, "device", None)
        print(f"Reusing profile job {args.profile_job} (device: {getattr(device, 'name', 'unknown')})")
        runtime_used = args.runtime
        target_model = compile_job.get_target_model() if compile_job else None
    else:                                                  # ---- fresh run
        device = pick_device(hub, args.device)
        print(f"Device: {device.name} ({device.os})")
        print("Uploading model ...")
        model = hub.upload_model(MODEL)

        # Try the ONNX-Runtime path first (matches deploy_on_snapdragon_npu.py), then QNN DLC.
        compile_job, runtime_used = None, None
        for runtime in ("onnx", "qnn_dlc"):
            print(f"Submitting compile job (target_runtime={runtime}) ...")
            job = hub.submit_compile_job(
                model=model, device=device, name="sme-loan-uplift-int8",
                input_specs={"features": ((1, 6), "float32")},
                options=f"--target_runtime {runtime}",
            )
            print("  ", job.url)
            status = job.wait()
            if status.success:
                compile_job, runtime_used = job, runtime
                break
            print(f"   compile with {runtime} failed: {getattr(status, 'status_message', status)}")
        if compile_job is None:
            sys.exit("Compile failed for all runtimes - open the job URLs above and read the logs.")

        print("Submitting profile job ...")
        target_model = compile_job.get_target_model()
        profile_job = hub.submit_profile_job(model=target_model, device=device, name="sme-loan-uplift-profile")
        print("  ", profile_job.url)

    status = profile_job.wait()
    if not status.success:
        sys.exit(f"Profile job failed: {getattr(status, 'status_message', status)}")
    metrics = parse_profile(profile_job.download_profile())

    result = {
        "device": getattr(device, "name", "unknown"),
        "device_os": getattr(device, "os", "unknown"),
        "hosted_on": "Qualcomm AI Hub",
        "target_runtime": runtime_used,
        "model": MODEL,
        "compile_job_url": compile_job.url if compile_job else None,
        "profile_job_url": profile_job.url,
        "timestamp_utc": datetime.datetime.now(datetime.timezone.utc).isoformat(timespec="seconds"),
        **metrics,
    }
    save_results(result)      # save NOW so a problem in the optional check below can never lose these numbers
    print("\n=== Real on-device results (Qualcomm AI Hub hosted device) ===")
    print(json.dumps(result, indent=2))
    print("\nSaved aihub_results.json and aihub_results.js")

    # ---- optional on-device correctness check (never fatal) ----------------
    if args.skip_inference:
        return
    try:
        inf_job = None
        if args.inference_job:
            inf_job = hub.get_job(args.inference_job)
        elif target_model is not None:
            print("Submitting on-device inference check ...")
            X = np.load(SAMPLES).astype(np.float32)
            inf_job = hub.submit_inference_job(
                model=target_model, device=device, name="sme-loan-uplift-check",
                inputs={"features": [X[i:i + 1] for i in range(len(X))]},
            )
            print("  ", inf_job.url)
        if inf_job is not None and inf_job.wait().success:
            match = inference_check(hub, inf_job)
            if match:
                result["device_vs_local_max_abs_uplift_diff"] = round(match[1], 5)
                result["inference_job_url"] = inf_job.url
                save_results(result)
                print(f"On-device uplift vs local INT8 model: max abs diff {match[1]:.5f} (output '{match[0]}')")
            else:
                print("Could not match an on-device output to the uplift values; skipping the comparison.")
    except Exception as e:
        print(f"[warn] on-device check skipped ({type(e).__name__}: {e}). Profiling results above are still valid.")


if __name__ == "__main__":
    main()
